# Generated by Django 6.0.1 on 2026-01-27 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solarpanel_quantity', models.IntegerField()),
                ('panelwatt', models.IntegerField()),
                ('backup_hours', models.IntegerField(default=0)),
                ('usable_power_kwh', models.FloatField()),
                ('total_daily_power_kwh', models.FloatField()),
                ('inverter_capacity_kwh', models.FloatField()),
                ('battery_capacity_kwh', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='power_calculation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanelCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances', models.JSONField()),
                ('panel_watt', models.IntegerField()),
                ('backup_hours', models.IntegerField(default=0)),
                ('max_inverter_capacity', models.FloatField()),
                ('total_daily_power_kwh', models.FloatField()),
                ('solar_panel_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_panel_calculation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
