# Generated by Django 6.0.1 on 2026-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solarpanel_quantity', models.IntegerField()),
                ('panelwatt', models.IntegerField()),
                ('backup_hours', models.FloatField()),
                ('usable_power_kwh', models.FloatField()),
                ('total_daily_power_kwh', models.FloatField()),
                ('inverter_capacity_kwh', models.FloatField()),
                ('battery_capacity_kwh', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanelCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliances', models.JSONField()),
                ('panel_watt', models.IntegerField()),
                ('backup_hours', models.FloatField()),
                ('max_inverter_capacity', models.FloatField()),
                ('total_daily_power_kwh', models.FloatField()),
                ('solar_panel_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
