# Generated by Django 6.0.1 on 2026-01-26 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('solar_panel', 'Solar Panel'), ('inverter', 'Inverter'), ('battery', 'Battery')], max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('cell_type', models.CharField(blank=True, max_length=100, null=True)),
                ('glass_thickness', models.CharField(blank=True, max_length=50, null=True)),
                ('max_power', models.CharField(blank=True, max_length=50, null=True)),
                ('max_system_voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_temperature', models.CharField(blank=True, max_length=100, null=True)),
                ('efficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
