# Generated by Django 6.0.1 on 2026-01-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
