# Generated by Django 6.0.1 on 2026-01-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0002_emailotp_reset_token_emailotp_reset_token_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='reset_token_expires_at',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='password_reset_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
